Add docker
Artemev1986/java-shareit pull request #5
Opened 2022-10-02 10:58 UTC by Artemev1986

2022-10-03 12:15 UTC, EvgenyKoptubenko commented on docker-compose.yml
> +version: '3.3'
Из коробки не запускается docker-compose

 => => extracting sha256:c05c789a4f46dbbc2b665e6ab66a96748905426bd2e4f07eef4127dc22794756                          4.1s
 => ERROR [2/2] COPY target/*.jar serverApp.jar                                                                    0.1s
------
 > [2/2] COPY target/*.jar serverApp.jar:
------
lstat /var/lib/docker/tmp/buildkit-mount012417535/target: no such file or directory
ERROR: Service 'server' failed to build : Build failed

2022-10-03 12:17 UTC, EvgenyKoptubenko commented
В файле readme.md должно быть описание проекта и инструкция как его запускать

2022-10-03 12:22 UTC, EvgenyKoptubenko commented on docker-compose.yml
> +services:
Еще нужен код (скрипт), с помощью которого можно проект запускать
docker-compose up -d
docker exec -it shareit-gateway ....

2022-10-03 12:22 UTC, EvgenyKoptubenko requested changes
Проект сделан очень хорошо. Проделана огромнейшая работа. Есть все несколько замечаний по запуску проекта.

2022-10-04 11:09 UTC, Artemev1986 commented
Добавил описание. С docsify еще пока не разобрался.

2022-10-05 10:29 UTC, EvgenyKoptubenko commented
Проект сделан хорошо. Запускается из коробки, тесты имеются, но в одном модуле, а один модуль без папки с тестами. Так же нет параметризованных тестов, но они не входят в текущую задачу.
Считаю, что работа сделана хорошо и можно принимать.

2022-10-05 10:29 UTC, EvgenyKoptubenko approved these changes
Проект сделан хорошо. Запускается из коробки, тесты имеются, но в одном модуле, а один модуль без папки с тестами. Так же нет параметризованных тестов, но они не входят в текущую задачу.
Считаю, что работа сделана хорошо и можно принимать

2022-10-05 12:24 UTC, merged